### ISSUE TITLE
Arctic/Longyearbyen timezone not recognized

### ISSUE THREAD

**Issue by juanyanezgc** [dlew/joda-time-android#102]
The timezone Arctic/Longyearbyen doesn't seem to be supported on Joda Time Android but it's supported by the Joda Time java library, I guess the timezones need to be updated

**Comment by dlew** [comment]
It's not that the timezones weren't updated, it's that "Arctic" region timezones weren't being parsed (due to an oversight). I'll fix this up and it'll go out in the next release.
