### ISSUE TITLE
Building with BUCK

### ISSUE THREAD

**Issue by benkc** [dlew/joda-time-android#105]
Hi!  I'm trying to make a BUCK build for joda-time-android.  Actually, I already had a working one for versions 2.7.2 and earlier, but I think the update that nuked Eclipse support also nuked some files I was depending on.

It fails when looking for a joda_zoneinfomap in R.raw.  (Actually first it failed to build because there was no R.raw, but I kludged my way around that.)  I poked around for some clue as to how to generate this myself, but I'm not seeing any instances of lowercase zoneinfomap anywhere in the project, so I'm not even sure where to start looking.

Is it perhaps generated by the stuff in here?

    buildSrc/src/main/groovy/net/danlew/android/joda/

Any other pointers to aid me in this endeavor?

Sorry for filing this as an "issue", I wasn't sure how else to get in touch.

If I get this all working again, would you guys be interested in me contributing the BUCK build file?  (I hear it's getting more popular, but I think it's still pretty niche...)

**Comment by dlew** [comment]
That's where it's generating all that data, yes. It's using the custom `compileTzData` task to do it.

I was uncomfortable with having compiled resources in the source. Pre-gradle there wasn't an easy way around it, but with Gradle it's possible to compile the resources and add them at build time. This helps prevent a lot of potential problems, like inconsistency between the source and the build.

All that said, I'm not exactly sure how you're going to do it with BUCK. You'd have to replicate the `compileTzData` step.

-----

Regarding adding a BUCK build file - what would be the advantage for the library?

**Comment by benkc** [comment]
Alright, I've hacked together something that seems to work -- it's putting ~477 files with names like "joda_america_indiana_indianapolis" in an output dir and sucking them into R.raw, and I'm seeing up-to-date timezone data when I build my app against that.  :)  And yeah, it took basically recreating the compileTzData stuff.

Adding a BUCK build file would only be useful to anyone else who tries to use joda-time-android with BUCK, of course.  That may well be just us.  *shrug*

Thanks for the help!

**Comment by felipecsl** [comment]
i just ran into this problem as well. @benkc do you mind sharing your workaround? thanks!

**Comment by benkc** [comment]
[BUCK.zip](https://github.com/dlew/joda-time-android/files/534695/BUCK.zip)
Hi @felipecsl, sorry for the slow reply, I missed the email.
In case you still need it, I'm attaching my BUCK file for jodatime_android.  You'll have to scrub it for a couple references to our build_helper and remove_logs stuff, but other than that it should be usable as-is.
Hopefully this attachment works!
[BUCK.zip](https://github.com/dlew/joda-time-android/files/534695/BUCK.zip)

**Comment by felipecsl** [comment]
@benkc thanks a lot for sharing we ended up using another workaround, which is to keep a fake class around that holds a reference to the R.raw fields accessed via reflection. I think you could also use [this](https://github.com/facebook/buck/commit/cae2a20393af522768a656216578ec7a302cc1f8) solution to keep the

**Comment by benkc** [comment]
Interesting, thanks!
My first attachment was missing a file, I've edited that for any future visitors to this thread.
