### ISSUE TITLE
Unexpected result with localDate now

### ISSUE THREAD

**Issue by DanChaltiel** [dlew/joda-time-android#106]
Hello the team !

```
LocalDate.now() //returns 2015-12-17, which is today
new LocalDate(LocalDate.now().toDate().getTime()); //returns 2015-12-16, which is yesterday
```

Can you reproduce this behavior ?
Is that a bug ?

At least this is very unexpected.

**Comment by dlew** [comment]
Closing, for two reasons:

1. This is a question about joda-time, not joda-time-android.

2. You're converting a `LocalDate` (part of joda-time) to `Date` (part of Java), then back again. `Date` is old and has no concept of timezones. Therefore it's a lossy conversion, so it makes sense that something might go wrong.
