### ISSUE TITLE
IOException opening resource when DateTime.parse() is called. This occurs in Android 5.0.2

### ISSUE THREAD

**Issue by IvanLopezCarreira** [dlew/joda-time-android#118]
W/System.err: java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxx/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]

**Comment by dlew** [comment]
Did you follow the instructions [here](https://github.com/dlew/joda-time-android#usage)?

**Comment by IvanLopezCarreira** [comment]
Yes. I use these version and initialize the library in Application onCreate();

**Comment by dlew** [comment]
Do you happen to be including both joda-time *and* joda-time-android?

I'm not really sure what's going on here because joda-time-android shouldn't be trying to load "org/joda/time/tz/data/ZoneInfoMap" at all; we use our own ZoneInfoMap.
