### ISSUE TITLE
Joda Time exception

### ISSUE THREAD

**Issue by Sutirth** [dlew/joda-time-android#120]
I get this exception as follows

java.lang.NoClassDefFoundError: net.danlew.android.joda.ResourceZoneInfoProvider

Using the latest gradle build. All the instruction are also followed according to usage article

Until and unless I include multidex the error is not resolved

**Comment by dlew** [comment]
This is a duplicate of #99.

Also, this is a legacy multidex problem, not an issue with the library itself. Please ensure your primary dex file includes joda-time-android.

**Comment by Sutirth** [comment]
@dlew Yep done the same for resolving the issue.Just was curious what exactly causes the issue
