### ISSUE TITLE
DateTimeZone UTC when installing apk 

### ISSUE THREAD

**Issue by nicdutil** [dlew/joda-time-android#121]
I can't get the proper default time zone set when installing my apk for the first time. 

snippet of code:

    public class MyApp extends Application {

        public static final String TAG = MyApp.class.getSimpleName();
 
       @Override
       public void onCreate() {
           super.onCreate();
          JodaTimeAndroid.init(this);
          Log.d(TAG, "TimeZone" + DateTimeZone.getDefault());    //outputs UTC 
          Calendar c = Calendar.getInstance();
          Log.d(TAG, "Calendar time:" + c);  // uses the correct time zone (America/New York)
          Log.d(TAG, "Joda Time:" + new DateTime());  // uses the UTC timezone
      }

Tested on : nexus 5 api 23 simulator  and kitkat api 19 simulator. Also tested on a kitkat device.

This happens only when I install the apk. If I kill the app and restart it, 
DateTimeZone.getDefault() outputs the correct America/New_York.

**Comment by dlew** [comment]
I'm not able to reproduce this behavior with the sample app. Can you reproduce it with the sample app from this project?

Also, how are you installing/starting the APK?

**Comment by nicdutil** [comment]
I did a new sample project using studio and it does grab 
the correct timezone on the first install. 

Not sure what the difference is yet between my toy project and other one i'm working on.

I'm installing the apks in the same way: as a debug build from studio.

**Comment by dlew** [comment]
My guess is that you're creating a `DateTimeZone` sometime before you call `JodaTimeAndroid.init()`, but only on the first start of the app. That would cause it to get stuck on UTC until a timezone change occurs.

**Comment by nicdutil** [comment]
Yes. That was it ! 

From the android doc:

public void onCreate ()
Called when the application is starting, before any activity, service, or receiver objects (excluding content providers) have been created.

I didn't read that line carefully. I have a content provider which will create a database (and a table with some initial data) upon installing the apk for the first time.  I used a LocalTime object to populate one of the field of that table. 

Moving JodaTimeAndroid.init to the onCreate callback of the content provider did the trick.

Might be good to add a footnote to your suggestion of where to put JodaTimeAndroid.init in your README.md file in case people have content providers in their app.

**Comment by nicdutil** [comment]
Thanks!
