### ISSUE TITLE
add methodscount

### ISSUE THREAD

**Issue by meierjan** [dlew/joda-time-android#126]
I would really appreciate adding the method-count to the `Readme.md` as serviceses like [methodcount.com](http://www.methodscount.com) are not working.

 * [methodscount.com link for library](http://www.methodscount.com/?lib=net.danlew%3Aandroid.joda%3A2.9.2)

```
> cat presentation/build/outputs/dexcount/debug.txt|grep joda
46       527      net.danlew.android.joda
4710     1042     org.joda
4710     1042     org.joda.time
270      20       org.joda.time.base
853      281      org.joda.time.chrono
120      20       org.joda.time.convert
541      66       org.joda.time.field
709      223      org.joda.time.format
154      57       org.joda.time.tz
```

I think this is worth mentioning.

**Comment by dlew** [comment]
methodscount.com works perfectly fine for me on the latest version: http://www.methodscount.com/?lib=net.danlew%3Aandroid.joda%3A2.9.3

**Comment by meierjan** [comment]
Wondering why this is not working for 2.9.2 but anyway...

I would welcome it to see the methodscound in the Readme.md as 5k methods is really heavy and new android developers don't know the dex-count issue.

**Comment by dlew** [comment]
I don't like badges.
