### ISSUE TITLE
Want a tz resource jar for pure-java testing

### ISSUE THREAD

**Issue by ypresto** [dlew/joda-time-android#127]
Unit testing pure java ~~library~~ classes without Robolectric causes "Resource not found" error (#17).
It can be run without robolectric if jar file which contains only tz resource files is provided.

### Example

build.gralde:

```groovy
dependencies {
    compile 'net.danlew:android.joda:2.9.3'
    testCompile 'net.danlew:android.joda.tzdb:2.9.3'
}
```

Application class:

```java
public void onCreate() {
    ...
    if (!isTesting) {
        JodaTimeAndroid.init()
    }
    ...
}

**Comment by dlew** [comment]
Usually people just include the plain `joda-time` dependency for unit tests, since it comes packaged with tzdb.

**Comment by ypresto** [comment]
Ah, sorry, we are testing pure-java classes IN Android application module. Not a independent library.

**Comment by dlew** [comment]
It is not pure Java if you're doing it inside of the Android framework.

That said, I see no reason to create a joda-time-android that includes the the tzdb in the JAR, because that's **exactly** what joda-time is already.

**Comment by ypresto** [comment]
> Usually people just include the plain joda-time dependency for unit tests,

Perhaps I was misunderstanding, did you meant something like below?

```groovy
dependencies {
    compile 'net.danlew:android.joda:2.9.3'
    testCompile 'joda-time:joda-time:2.9.3'
}
```

(There is similar question and solution on ThreeTenABP repo. https://github.com/JakeWharton/ThreeTenABP/issues/14#issuecomment-142049959 )

**Comment by dlew** [comment]
Yes, exactly.

**Comment by ypresto** [comment]
https://github.com/dlew/joda-time-android/issues/17#issuecomment-166010051
Omg there was same Q&A here... I'm sorry for duplicated issue :sob: Thanks for replies..!
