### ISSUE TITLE
Don't accidentally keep the joda_keep file

### ISSUE THREAD

**Issue by dlew** [dlew/joda-time-android#132]
Because https://github.com/dlew/joda-time-android/blob/master/library/src/main/res/raw/joda_keep.xml references itself, so it ends up getting packaged.

**Comment by zincle** [comment]
@dlew My apk size is increased with these localised files, is there any way I can exclude them from library, without using your library as module (currently using as implementation via gradle)

**Comment by dlew** [comment]
`joda_keep.xml` doesn't apply to the localized files, only the timezone data itself, which is a necessary component of this app. The localized files should be removed if you use

```
minifyEnabled true
shrinkResources true
```

in you build.gradle.

**Comment by zincle** [comment]
Yeah my bad! I am already using mimifyEnabled and shrinkResources, I actually meant the timezone data strings, not the localized strings, but as you mentioned it is necessary component, so cant be detached from library, thanks.
