### ISSUE TITLE
v2.9.4 doesn't exist on any repositories

### ISSUE THREAD

**Issue by meNESS** [dlew/joda-time-android#141]
Hi,

```gradle
compile 'net.danlew:android.joda:2.9.4'
```

throws _Could not find net.danlew:android.joda:2.9.4_ exception. It may doesn't exist on any repositories yet.

**Comment by dlew** [comment]
I need to push the latest out there; this got merged a bit prematurely, sorry.

**Comment by dlew** [comment]
There, it's been released and should show up on maven central soon.
