### ISSUE TITLE
"You have to ALSO import JodaTime"

### ISSUE THREAD

**Issue by Mithrandir21** [dlew/joda-time-android#149]
I suggest adding a line in the ReadMe saying that anyone wanting to use the library has to ALSO add the JodaTime library in addition to this library.

**Comment by dlew** [comment]
If you're using Gradle it will automatically import joda-time as a transitive dependency.

**Comment by Mithrandir21** [comment]
Than your Gradle is something my Gradle is not doing.

**Comment by dlew** [comment]
What shows for joda-time-android if you run the Gradle `dependencies` task on your app's directory? E.g. `./gradlew :app-dir:dependencies`.

**Comment by Mithrandir21** [comment]
You are correct in assuming that JodaTime is a dependency of this library, as seen in the Gradle Dependencies check:

    \--- net.danlew:android.joda:2.9.4.1
     \--- joda-time:joda-time:2.9.4

But still can't manage to import anything from the Joda packages, like DateTime, DateTimeZone, etc.
Could there be any issues with using Gradle 2.1.2?

**Comment by dlew** [comment]
Are you removing it via Proguard or something?

A warning: This is quickly moving outside the bounds of the joda-time-android issue tracker, which is for issues with the library itself. This problem sounds more like an issue with your own build setup, which is preventing dependencies from being consumed.

**Comment by Mithrandir21** [comment]
I understand.
I will continue looking into to it as you suggest. Thank you for indulging me this far.
