### ISSUE TITLE
NullPointerException: Attempt to read from null array

### ISSUE THREAD

**Issue by diegoRodriguezAguila** [dlew/joda-time-android#151]
Hello I'm having a problem with dates received from a web service.
when I try to call toString: `startDate.toString("EE dd, MMM: HH:mm")` it throws this exception:
```
java.lang.NullPointerException: Attempt to read from null array
at org.joda.time.tz.CachedDateTimeZone.getInfo(CachedDateTimeZone.java:143)
at org.joda.time.tz.CachedDateTimeZone.getOffset(CachedDateTimeZone.java:103)
at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:722)
at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:535)
at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:671)
at org.joda.time.base.AbstractDateTime.toString(AbstractDateTime.java:328)
at com.lasalle.mobile.model.TimeSlot.toString(TimeSlot.java:28)
at com.lasalle.mobile.view.adapters.spinner.TimeSlotAdapter.getView(TimeSlotAdapter.java:54)
```
I deseralize via Gson with the custom deserializer:
```
public DateTime deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context)
            throws JsonParseException {
        // Do not try to deserialize null or empty values
        if (json.getAsString() == null || json.getAsString().isEmpty()) {
            return null;
        }

        final DateTimeFormatter fmt = ISODateTimeFormat.dateTimeParser();
        return fmt.parseDateTime(json.getAsString());
    }
```
The dates sent from my server DO have ISO format, so is not a deseralization related exception.
i.e.: `2016-09-12T10:00:00-0600`

As a side note, the problem only occurs when re-running the app. For example, if I make a full clean install, it doesn't throw that exception. Maybe is a Joda initialization problem?.
I hope I can get help, thank you in advance

**Comment by dlew** [comment]
Are you initializing the library *before* trying to parse the dates?

**Comment by diegoRodriguezAguila** [comment]
Indeed,  I'm initializing it in the application's onCreate as required in the docs

**Comment by dlew** [comment]
I'm not able to reproduce the issue. I think I need a bit more to go on before I can diagnose it.

**Comment by diegoRodriguezAguila** [comment]
I have managed to fix it. The problem was in the serialization,  not in GSON but in Kyro. As I'm using [PaperDb](https://github.com/pilgr/Paper) as a "caché" for the web service results, and It uses Kyro serialization to save the objects.

 It didn't threw any serialization exception, so I thought it was fine, later I found out it requires a JodaTimeSerializer to be set up, which they also provide.

Everything is working fine now, sorry for the misleading issue.

**Comment by Dosssik** [comment]
@diegoRodriguezAguila Hi! I've got exactly same issue - we persist DateTime in PaperDb. May i ask you, how did u overcome this problem?

**Comment by diegoRodriguezAguila** [comment]
@Dosssik I don't have the specific serializer right now, but you may just implement a kyro serializer for joda datetime objects, this is a kyro serializer for uris: https://github.com/diegoRodriguezAguila/SGAM.Elfec.Mobile/blob/master/app/src/main/java/com/elfec/sgam/local_storage/serializers/KryoUriSerializer.java
