### ISSUE TITLE
joda-time-android in a library?

### ISSUE THREAD

**Issue by p-fischer** [dlew/joda-time-android#163]
Hi,
I'm using joda-time-android in some apps and I'm very happy with it. Thanks a lot to the creators!

Here's my question:
I'm currently using joda time (the non-android variant) in an Android library.
Because of the advantages mentioned (memory footprint) I'd like to switch to joda-time-android too.

My concern is the init call:`JodaTimeAndroid.init(this);`
My library actually requires initialization too and is passed a context. Hence, I can make the joda time init call there.
However, I see the scenario, where the user of my library sees joda-time is available and wants to use it before my library is initialized. (What happens in that case anyway?)

Do you have any thoughts on that or even experience?

**Comment by dlew** [comment]
It's setup so that it only initializes once, even if called from multiple places, so it should be safe: https://github.com/dlew/joda-time-android/blob/master/library/src/main/java/net/danlew/android/joda/JodaTimeAndroid.java

**Comment by p-fischer** [comment]
Yep, I see.
However, in my scenario the developer using my lib sees DateTime is available and thinks he can use it right away. Is there a way I can ensure `JodaTimeAndroid.init(this);` has been called before my library is getting initialized in the app?

**Comment by dlew** [comment]
Unfortunately, no. I think it's on the developer, though, if they start using a dependency without doing any research (at all) on it first.

**Comment by p-fischer** [comment]
Sounds reasonables. Developers are clever people after all :)
