### ISSUE TITLE
Use Android Timezone

### ISSUE THREAD

**Issue by metinkale38** [dlew/joda-time-android#165]
Hey,

i know JodaTime is using its own TimeZone Database which gets updated more often than a Android OS, normally this sounds good.

The problem i have:
Turkey decided recently to stay in +3 the whole year, JodaTime updated and corrected this, what is normally fine.
But most of my users changed the Time to be correct instread of the TimeZone, that means JodaTime will show another Time than the system time (because they use the same "wrong" time, and calculate it with another tz).
Lots of my users complained about that...

i tried 
   DateTimeZone.setDefault(DateTimeZone.forTimeZone(TimeZone.getDefault()));
but it is still the same.

i cant test myself, but users complain, and after i say, they have to correct their timezone, it works correct...

what could be the problem, and what can i do to fix that problem?

**Comment by dlew** [comment]
You could call `DateTimeZone.setProvider()` (like [our init method does](https://github.com/dlew/joda-time-android/blob/master/library/src/main/java/net/danlew/android/joda/JodaTimeAndroid.java)) and provide your own Android-tz-based provider.

**Comment by metinkale38** [comment]
Thank you, i will try that...

But why does DateTimeZone.setDefault(DateTimeZone.forTimeZone(TimeZone.getDefault())); not work?

Should'nt it set the Phones Timezone to Joda?

**Comment by dlew** [comment]
The short answer is: Your code actually does nothing. Joda-time uses `TimeZone.getDefault()` anyways.

The long answer is that if the device's current time is set incorrectly then you won't be able to calibrate anything. Check out this setup:

- The OS thinks that UTC time is 07:00 (the correct actual UTC time).
- OS TZ displays as 09:00 because it uses out-of-date information (think it's still +2).
- Joda-time TZ thinks it's 10:00 because it uses correct information (+3).

If your users changed the timezone to something that was also +3, then we'd be fine. But instead they changed the system clock, so this happens:

- The OS thinks that UTC time is 08:00 (which is incorrect).
- OS TZ displays as 10:00 (+2 of incorrect UTC).
- Joda-time TZ displays as 11:00 (+3 of incorrect UTC).

Having thought about it more, I'm not sure you can actually fix this problem. If your OS is lying about what UTC time is, there's no way to know what the actual time is (short of pinging time servers yourself, in your app).

**Comment by metinkale38** [comment]
if somebody needs it, my code is below, everybody can use it freely...

it simply wraps androids TimeZone Objects with an Joda compatible DateTimeZone Object. it is a bit hacky, though, it is using reflections ;)

@dlew i dont know how you want it to be, but i think it would'nt be a bad idea to have this as default (or atleast as an option) in your library. problems like i had can be quite confusing and it is normally expected to have the same time on  the phone and in the app...


```
import android.util.ArraySet;

import org.joda.time.DateTimeZone;
import org.joda.time.tz.Provider;

import java.lang.ref.WeakReference;
import java.lang.reflect.Field;
import java.util.Collections;
import java.util.HashMap;
import java.util.Set;
import java.util.TimeZone;

/**
 * Created by metin on 13.02.2017.
 */
public class AndroidTimeZoneProvider implements Provider {
    private HashMap<String, WeakReference<DateTimeZone>> cache = new HashMap<>();

    public AndroidTimeZoneProvider() {

    }

    @Override
    public DateTimeZone getZone(String id) {
        if (id.equals("UTC")) return DateTimeZone.UTC;
        WeakReference<DateTimeZone> wr = cache.get(id);
        if (wr != null) {
            DateTimeZone dtz = wr.get();
            if (dtz != null) return dtz;
        }
        TimeZone tz = TimeZone.getTimeZone(id);
        DateTimeZone dtz = new MyDateTimeZone(id, tz);
        cache.put(id, new WeakReference<>(dtz));
        return dtz;
    }

    @Override
    public Set<String> getAvailableIDs() {
        ArraySet<String> set = new ArraySet<>();
        Collections.addAll(set, TimeZone.getAvailableIDs());
        return set;

    }


    private class MyDateTimeZone extends DateTimeZone {
        private TimeZone tz;
        private long[] transitions = new long[0];

        MyDateTimeZone(String id, TimeZone tz) {
            super(id);
            this.tz = tz;

            try {
                Field f = tz.getClass().getDeclaredField("mTransitions");
                f.setAccessible(true);
                long[] transitions = (long[]) f.get(tz);
                if (transitions == null) return;
                this.transitions = new long[transitions.length];
                System.arraycopy(transitions, 0, this.transitions, 0, transitions.length);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        @Override
        public String getNameKey(long l) {
            return null;
        }

        @Override
        public int getOffset(long l) {
            return tz.getOffset(System.currentTimeMillis());
        }

        @Override
        public int getStandardOffset(long l) {
            return tz.getRawOffset();
        }

        @Override
        public boolean isFixed() {
            return !tz.useDaylightTime();
        }

        @Override
        public long nextTransition(long l) {
            int i = 0;
            long time = System.currentTimeMillis() / 1000;
            while (i < transitions.length && transitions[i] < time) {
                i++;
            }
            return i >= transitions.length ? 0 : transitions[i];
        }

        @Override
        public long previousTransition(long l) {
            int i = -1;
            long time = System.currentTimeMillis() / 1000;
            while (i + 1 < transitions.length && transitions[i + 1] < time) {
                i++;
            }
            return i >= 0 && i >= transitions.length ? 0 : transitions[i];
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof MyDateTimeZone)) return false;
            return ((MyDateTimeZone) o).getID().equals(getID());
        }
    }
}
```

**Comment by MenoData** [comment]
I have experienced the same problem when using an independent timezone database. So what is still the same (reasonable expectation) is the local time on both devices with user-workaround or devices with up-to-date timezone database in OS. This has caused me to offer a new API-method in my own time library Time4A, see: http://time4j.net/javadoc-en/net/time4j/SystemClock.html#inPlatformView--

**Comment by Albul** [comment]
Time4A is great library, but it is time consuming to port Joda Time in your app to time4a. And it seems JodaTime is still most performant library among others. I have create a couple of [banchmarks here](https://gitlab.com/olekdia/common/utils/java-benchmarks/tree/master/src/main/java/com/olekdia/datetime): 
So I forked Joda Time and removed IANA databases, and use system's timezones instead.
https://gitlab.com/olekdia/common/utils/support-joda-time

**Comment by MenoData** [comment]
@Albul First to say, migration to another library does only make sense if either new features are necessary (then consider partial migration) or if the size of migration work is small. In your case, forking JodaTime might be the best action regarding the background that JodaTime is no longer in active development.

The performance is rather a secondary aspect here. About your benchmarks, it is interesting to see it, and I can take the benchmarks as inspiration to do some more inlining in Time4A where appropriate. But we should also see that your benchmarks are not always comparing comparable things. One such example is that JodaTime returns weekday-numbers as ints (which is naturally quicker) while Time4A and java.time return enums (so you measure an extra method call to extract the number). And I have noticed a lot more such examples (which is out of scope of this little comment here) so your statement about Jodas performance should rather be taken with caution. I would also measure formatting and parsing (and bet that Time4J/A is the best here ;-)).

**Comment by dlew** [comment]
GitHub issues are for issues; it's really not the place to have a debate about various alternative libraries.

Also note that you do not need to fork joda-time in order to provide your own library. [As noted above](https://github.com/dlew/joda-time-android/issues/165#issuecomment-279382867), you can provide your own TZ provider that uses the system timezones. You can depend on the joda-time-no-tzdb artifact (like this library does) to get a version of joda-time minus their resources, so you don't double-up on tzdata.
