### ISSUE TITLE
Failed resolution of: Lnet/danlew/android/joda/R$raw;

### ISSUE THREAD

**Issue by RandomCouch** [dlew/joda-time-android#166]
Hi, I'm trying to package a .jar to use it in Unity game engine, I realize this issue doesn't exist when using this library natively, however I'm completely blocked on this and just trying to see if I can get help with this issue here.

I'm trying to run JodaAndroidTime.init, however when I do that I get:
java.lang.NoClassDefFoundError: Failed resolution of: Lnet/danlew/android/joda/R$raw;
It is loading the rest of the library, but not the R class, I think this is because Unity isn't generating the R.class since I'm just using the .jar file (which doesn't contain the R.java class). I'm wondering if there can be a solution to this like having JodaAndroidTime use Unity's own generated R class, which should be com.myPackageName.projectName.R

Thanks for any help on this

**Comment by dlew** [comment]
Sorry for the slow reply, been on vacation.

I don't know anything about Unity, but it seems like it may just make more sense to use vanilla joda-time if all you can include is a JAR file. joda-time-android is specially optimized for Android APKs and requires the usage of the resource system, so if Unity can't use resources then this library won't help.
