### ISSUE TITLE
How to use joda-time-android in java-modules?

### ISSUE THREAD

**Issue by tmtron** [dlew/joda-time-android#167]
I have an android application with one android application module (app) and a java-only module (javamodule).

How can I use joda-time in both?  
e.g. when I simply add the `net.danlew:android.joda` dependency to both, the build will complain, that the java-module depends on an Android Library.

> Error:Module 'App:javamodule:unspecified' depends on one or more Android Libraries but is a jar

**Comment by liminal** [comment]
android-joda is just 'joda-time:joda-time:2.9.6:no-tzdb'. with an android wrapper. Try using that dependency in the pure java module (maybe as a 'provided' dependency, I'm not 100% on this) and you _should_ be all good.

**Comment by liminal** [comment]
Clarification:

In the app module you declare the dependency on joda-time-android
app/build.gradle:
```
apply plugin: 'com.android.application'

android {
...
}

dependencies {
        compile 'net.danlew:android.joda:2.9.6'
}
```
And in the java library you declare that all the classes in joda-time will be available at run time basically.
lib/build.gradle:
```
apply plugin: 'java'

dependencies {
     provided 'joda-time:joda-time:2.9.6:no-tzdb'
}
```

**Comment by dlew** [comment]
Sorry for the late reply (been on vacation), but liminal has the right answer here.

More discussion on this can be found here: https://github.com/dlew/joda-time-android/issues/127
