### ISSUE TITLE
Usage in unit testing

### ISSUE THREAD

**Issue by kaushikgopal** [dlew/joda-time-android#17]
When unit testing the Android app (junit.framework.TestCase or Junit 4 tests from a pure submodule) joda-time-android cannot be used as it requires a context as part of the `JodaTimeAndroid.init`ialization.

The alternative is to obviously just use joda-time for submodules and converting `TestCase`s to `AndroidTestCase`s (in the process getting hold of a context for initialization). 

In you experience have you had to deal with a similar case and if so did you choose an alternative nicer approach for unit testing? Conceptually it would be nice to have the exact same JodaTime library used for both testing and production, but is this just a limitation that can't be overcome?

Cheers

**Comment by danielgomezrico** [comment]
@dlew can you show please how you use joda-time instead of `joda-time-android` for the pure java libraries? 

I´m trying to do just unit testing with MVP but I get when I try to use joda time android, trying to mock it too but don´t work.

```
public class LoginActivity extends MyBaseActivity implements LoginView {
```
Error:
```
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: sun.misc.Launcher$AppClassLoader@7852e922
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:210)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:127)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:86)
	at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:514)
	at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:413)
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:216)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:151)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:61)
	at org.joda.time.DateTime.<init>(DateTime.java:171)
	at org.joda.time.DateTime.now(DateTime.java:89)
```

Why?

**Comment by dlew** [comment]
I'm a bit confused. How is that a pure java library if you're using `Activity`?

**Comment by danielgomezrico** [comment]
@dlew ! I copied the wrong line :P it happens when I try to create a new DateTime for mocking.

**Comment by dlew** [comment]
You're including joda-time-android when you should just be using joda-time. I can't help without seeing what you're doing in gradle, but that's the gist.

**Comment by aashrairavooru** [comment]
This is a bit late but if anyone stumbles here, unfortunately not all of modules were pure java, but thankfully most of the package names and functionality in joda time android is similar to joda time, so for running jvm unit tests you can do something like

```testCompile "joda-time:joda-time:${jodaTimeVersion}"```

Although this won't work for classes or modules where you are using jodaTimeAndroid exclusive classes, but in my case i was able to successfully use it in a lot of places

@dlew i am assuming there shouldn't be any side effects with this approach like possible flaky tests

**Comment by dlew** [comment]
That's what we do internally. In fact, nowadays joda-time-android has a transitive dependency on joda-time, so you're using exactly the same classes. The only difference is the `ZoneInfoProvider`.

**Comment by aashrairavooru** [comment]
True, so I guess most people can do jvm tests without any problem for the
most part
