### ISSUE TITLE
Cannot find Joda classes after gradle sync

### ISSUE THREAD

**Issue by georgikoemdzhiev** [dlew/joda-time-android#171]
Hello! After adding the library to my project and synced Android Studio  could not find Joda library calsses like DateTime, Interval etc. I did instantiated it in the Application onCreate method. Maybe I am doing something wrong.

**Comment by dlew** [comment]
Could not find in what way? Does it not compile?

**Comment by georgikoemdzhiev** [comment]
Hi! Yes, it does compile fine. However, Android Studio seems to be not able to recognize the library so it can do the necessary imports. I have to mention that at very first compile (first use of the library) everything was fine. However, since I have had removed the library from the gradle file > synced it a couple of items (I was not sure if I wanted to use it) it came to the above mentioned stage.

**Comment by dlew** [comment]
I'm even more confused now. You say you removed the library from the gradle file. That means the library should no longer be present. This makes sense to me.

**Comment by georgikoemdzhiev** [comment]
Yes, and then I added it again. When I tried to sync Gradle files it was not able to recognise Joda library classes. Anyway, if that has not happened before, it is probably something on my system. I will close the issue now.
