### ISSUE TITLE
ISOChronology Timezone.getDefault returns UTC 

### ISSUE THREAD

**Issue by slimeradio** [dlew/joda-time-android#179]
Hi! 
Found bug, when calling ISOChronology.getInstance() before JodaTimeAndroid.init(context), causes DateTimeZone.getDefault() return UTC timezone only.

**Comment by dlew** [comment]
That's not a bug. [The instructions state](https://github.com/dlew/joda-time-android#usage) that you should call `JodaTimeAndroid.init()` before you can properly use joda-time-android.

**Comment by slimeradio** [comment]
I mean maybe you should rise exception? Its not normal behavior and finding this bug took a lot of time for me.

**Comment by dlew** [comment]
joda-time is what implements the default behavior when you haven't provided your own timezone data, and at this point it's in maintenance mode, so I doubt they'd change the behavior at this point.

Without doing some tricky automatic hooks, I wouldn't be able to make this library automatically work (or automatically fail).
