### ISSUE TITLE
 org.joda.time.IllegalFieldValueException: Value 0 for monthOfYear must be in the range [1,12]

### ISSUE THREAD

**Issue by Shahroz16** [dlew/joda-time-android#18]
10-02 17:52:25.617: E/AndroidRuntime(24239): org.joda.time.IllegalFieldValueException: Value 0 for monthOfYear must be in the range [1,12]
10-02 17:52:25.617: E/AndroidRuntime(24239):    at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:252)
10-02 17:52:25.617: E/AndroidRuntime(24239):    at org.joda.time.chrono.BasicChronology.getDateMidnightMillis(BasicChronology.java:612)
10-02 17:52:25.617: E/AndroidRuntime(24239):    at org.joda.time.chrono.BasicChronology.getDateTimeMillis(BasicChronology.java:159)
10-02 17:52:25.617: E/AndroidRuntime(24239):    at org.joda.time.chrono.GregorianChronology.getDateTimeMillis(GregorianChronology.java:1)
10-02 17:52:25.617: E/AndroidRuntime(24239):    at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:120)
10-02 17:52:25.617: E/AndroidRuntime(24239):    at org.joda.time.LocalDate.<init>(LocalDate.java:457)
10-02 17:52:25.617: E/AndroidRuntime(24239):    at org.joda.time.LocalDate.<init>(LocalDate.java:436)

**Comment by rajuginne** [comment]
tring replace but
private DateTime convertToDateTime(String stringToConvert) {
         String[] newStringArray = convertStringToArray(stringToConvert);
         LocalDate mLocalDate = new LocalDate(Integer.parseInt(newStringArray[2].trim()),
                 Integer.parseInt(newStringArray[0].trim()),
                 Integer.parseInt(newStringArray[1].trim()));
         return mLocalDate.toDateTime(LocalTime.fromDateFields(mLocalDate.toDate()));
//
       
     }
  private DateTime convertToDateTime(String stringToConvert) {
         String[] newStringArray = convertStringToArray(stringToConvert);


Interval mInterval = new Interval(Integer.parseInt(newStringArray[2].trim()),
Integer.parseInt(newStringArray[0].trim()),
                 Integer.parseInt(newStringArray[1].trim()));
//cannot resolve interval (int int int)  error


         return mLocalDate.toDateTime(LocalTime.fromDateFields(mLocalDate.toDate()));

         Interval interval = new Interval(start, end);*/

}
