### ISSUE TITLE
Use Android Timezones instead of Database

### ISSUE THREAD

**Issue by metinkale38** [dlew/joda-time-android#182]
Hey,

i wonder, whether there is a reason to use the Timezones Database instead of the Android Timezones directly? 
Of course, it might be sometimes good to have a newer database version, but most of the time it makes problem, when they are not in sync... Apps using Joda will show another "Current Local Time" than the OS.

As solution i had a TimeZone Provider: https://github.com/dlew/joda-time-android/issues/165

i am using it for a while, and did not have any issues till now...

it might be a good idea, to make this default (or at least configurable)

or is there something i miss, why thats not a good idea?

**Comment by dlew** [comment]
Using up-to-date tzdata is one of the primary goals of joda-time-android. If you are using Android-based tzdata then it would make more sense to just use joda-time plain with your own provider.

**Comment by metinkale38** [comment]
yes, i do.

but lot's of people directly use this library, because the other one does not directly work, and can't see the issues, which might appear in other countries/devices.

it's not a problem for me, it is only a suggestion, because i saw a few more people complaining about that (e.g. on StackOverflow)

if you do not want that, you can just close this ticket...
