### ISSUE TITLE
withPivotYear() has no effect

### ISSUE THREAD

**Issue by abiemann** [dlew/joda-time-android#186]
The following test code :

`DateTime jodaTime = new DateTime(72, 0+1, 1, 0, 0);// January 1, 1972`
`DateTimeFormatter formatter = DateTimeFormat.forPattern("d MMMM, yyyy");`
`String formattedDate = formatter.withPivotYear(1975).print(jodaTime);`
`Log.d("test", formattedDate);`

**outputs :**

> D/test: 1 January, 0072

**I expected :** 

> 1 January, 1972

**Comment by dlew** [comment]
This looks like an issue with [joda-time](https://github.com/JodaOrg/joda-time), not joda-time-android. I suggest filing this bug there.
