### ISSUE TITLE
Comparison to ThreeTenABP

### ISSUE THREAD

**Issue by feinstein** [dlew/joda-time-android#193]
I am sorry to ask you this bluntly, but how does your solution compares to:
https://github.com/JakeWharton/ThreeTenABP

I am evaluating a good way to implement JSR-310 on old devices and I can't figure how you two are different and which one to choose.

**Comment by dlew** [comment]
https://github.com/JakeWharton/ThreeTenABP/blob/master/README.md#why-not-use-joda-time

**Comment by feinstein** [comment]
@dlew that's not my question. I am not asking why not to use Joda, I am asking the difference between your library and ThreeTenABP. As far as I can see, you both implement a simplified version of Joda Time, yet avoiding all its problems on Android, with the same strategy.

**Comment by dlew** [comment]
You asked the exact same question in https://github.com/JakeWharton/ThreeTenABP/issues/61 and got your answer. I don't know what more you want.

**Comment by feinstein** [comment]
I asked there too so I could be fair with each other, if I just asked in one place this would be biases.

The answer he gave me doesn't makes much sense. He points out to a link about "Why not to use Joda-Time", I think he got confused about your library's name with he original one.

**Comment by dlew** [comment]
joda-time-android is built on top of joda-time. They the same, except for where the timezone data is provided from. This is explained in the [README](https://github.com/dlew/joda-time-android#why-this-library).

**Comment by feinstein** [comment]
I see, it wasn't clear for me they where the same but the TZ data came from a different place, I just thought you chanced the way the Library is loaded. Thank you for the clarification.

Now I believe the difference count  your library and ThreeTenABP is ThreeTenABP also simplifies the method count.

**Comment by MenoData** [comment]
@feinstein I am not sure that you are aware of the fact that ThreetenABP and Joda-Time-Android are both wrappers around two different libraries and APIs. ThreetenABP encapsules the backport of Threeten-project which is closely (but not exactly) related to JSR-310. But Joda-Time-Android is a wrapper around Joda-Time which is completely different from JSR-310 or the Threeten-project (although the primary developer of both libraries is indeed the same person).

**Comment by feinstein** [comment]
Yeah, took me a while to realize that. At first I thought they were all wrappers to backport Joda-Time somehow, but then I realized I was missing the details. Thanks for y

**Comment by MenoData** [comment]
@feinstein Okay, but which problem do you try to solve? You say you want to implement JSR-310 on old devices. If so then why not use ThreetenABP? What does prevent you from using that almost-jsr-310-implementation (adapted for Android)? I am just curious because I am also developing and distributing my own time library looking for possible enhancements.

**Comment by feinstein** [comment]
I want to use a good time library, that's small (because of dex method count), well documented and can be used in  older versions of Android (Lollipop at least, KitKat preferably). So far ThreeTenABP is my choice, specially for its size and resemblence to Joda-Time.
