### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by guidedways** [dlew/joda-time-android#204]
I'm seeing this at launch all of a sudden after using the new bundle format in Android Studio:

```java
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.danlew.android.joda.R$raw" on path
```

Any ideas?

**Comment by dlew** [comment]
No ideas, I haven't started using bundles yet myself.

You should file a bug report with Android Studio, not joda-time-android.
