### ISSUE TITLE
Incorrect TimeZone on app first run then ok after app restart, with factory default device

### ISSUE THREAD

**Issue by ArilesGit** [dlew/joda-time-android#205]
Hi,

I think I'm facing a timeZone bug.
It only happens when I first run my app. Here is how I reproduce the bug :

   1. I reset my android 6.0 tablet to factory default. At bootup, it comes with an older version of my app installed as a system-app which starts automatically.
   2. I install a newer version through adb shell.
   3. I start the app and display date and time which is wrong because of the timeZone (UTC instead of Europe/Amsterdam).
   3. I kill the app and start it up again. Now, it displays the right date & time with the Europe/Amsterdam timeZone.

TimeZone is correct when I use java.util's TimeZone.

`DateTimeZone.getDefault() => "UTC"`
`TimeZone.getDefault()        => "Europe/Amsterdam"`

Thank your work and  for helping.

[StackOverflow question](https://stackoverflow.com/questions/51159685/android-joda-time-incorrect-timezone-on-app-first-run-then-ok-after-app-restart)

**Comment by dlew** [comment]
I've been ruminating on this for a couple days and I honestly don't know what's going on. `DateTimeZone.getDefault()` should be based off of `TimeZone.getDefault()`.

I'd have to have more code to reproduce, or maybe you could try to figure out who is setting the default incorrectly.

**Comment by ArilesGit** [comment]
Hello !
Sorry for the late reply.

For now, I forced it with `DateTimeZone.setDefault(DateTimeZone.forID(...))` when the `Application` is created, which is bad... but it saves us sometime.

I will try to look into this soon and keep you posted.

**Comment by ArilesGit** [comment]
Hello !
I may have a little info about this issue :
`TimeZone.getDefault().getID()` returns `Europe/Amsterdam`, whereas
`DateTimeZone.getDefault().toTimeZone().getID()` returns `UTC`.

@dlew am I missing something ?

**Comment by dlew** [comment]
Isn't that just what was posted earlier? I can't being to piece together *why* that is happening without a reproduction on my end.

**Comment by ArilesGit** [comment]
You are right, I thought I was able to reproduce it in the emulator without the 1st step
> 1. I reset my android 6.0 tablet to factory default. At bootup, it comes with an older version of my app installed as a system-app which starts automatically.

But, it turned out I forgot to call `JodaTimeAndroid.init(context)` this time. Sorry about that.
I'll keep looking and I'll update this issue if I find a way to reproduce it without having to reset the device to factory default.

Thanks again for being available. :medal_sports:

**Comment by dlew** [comment]
Closing for lack of reproduction. If you have a repro, I'd be happy to look into it more.
