### ISSUE TITLE
IllegalArgumentException: Invalid Format, but no information about where it's malformed

### ISSUE THREAD

**Issue by PacoSwifty** [dlew/joda-time-android#213]
We're seeing the following crash:

java.lang.IllegalArgumentException: Invalid format: "Sun, 06-Oct-2019 17:15:56 GMT"

It pops up very occasionally with only a handful of specific users, but we don't get any additional info in the stacktrace about what's wrong with the format provided. When we manually insert timestamps from the crash reports while debugging/run them through our unit tests, we have no problems and don't see the crash. We have been unable to reproduce the issue but are still seeing new instances of it in New Relic. 

This is the method in question:
   ```
 public static DateTime getDateTimeFromLegacyFormat(String oldFormat) {
        DateTimeFormatter parser = DateTimeFormat.forPattern("EEE, dd-MMM-yyyy HH:mm:ss z") 
        return parser.parseDateTime(oldFormat);
    }
```
Where oldFormat is the legacy timestamp (Sun, 06-Oct-2019 17:15:56 GMT) 

Here are a few of the other timestamps from crash reports, all of which pass our unit tests. 
MESSAGE Invalid format: "Tue, 03-Sep-2019 21:43:15 GMT"
MESSAGE Invalid format: "Fri, 23-Aug-2019 19:36:21 GMT"
MESSAGE Invalid format: "Sun, 13-Oct-2019 06:17:58 GMT"
MESSAGE Invalid format: "Fri, 02-Aug-2019 18:10:54 GMT"

Does anything here jump out as being an obvious problem that we're just missing?

**Comment by dlew** [comment]
There's nothing obviously wrong as far as I can tell. I would guess that maybe it's a device that's got some weird set of locale rules or something that's causing parsing to fail?

Regardless, this may be more of a core joda-time issue than one with joda-time-android; we don't touch the parsing code at all.

**Comment by PacoSwifty** [comment]
I'll try posting over there and see if it sparks anything. Thanks for your quick reply.
