### ISSUE TITLE
AGPBI: {"kind":"error","text":"Program type already present: net.danlew.android.joda.R$plurals","sources":[{}],"tool":"D8"}

### ISSUE THREAD

**Issue by ColtonIdle** [dlew/joda-time-android#224]
Added the firebase-core dependency to my application and now I got this error.

AGPBI: {"kind":"error","text":"Program type already present: net.danlew.android.joda.R$plurals","sources":[{}],"tool":"D8"}

Prevents me from building. It may be D8 related I guess, but I wanted to put some feelers out to see if @dlew knew what could be the cause/solution.

I'm using latest AS 3.5 Canary 13, latest gradle, latest AGP, latest Kotlin plugin.

**Comment by dlew** [comment]
Hmm, I've never seen that before, sorry. Is it possible that firebase-core is bringing in joda-time-android on its own in some weird way (e.g. copy/pasting the code)?

**Comment by ColtonIdle** [comment]
Not too sure. I was trying to resolve this so I could at least build and the solution I got to was making sure that I was using all of the latest versions of Firebase. I updated my firebase analytics to the newest dot release and everything worked again.
