### ISSUE TITLE
Update to joda time version 2.10.2

### ISSUE THREAD

**Issue by emartynov** [dlew/joda-time-android#225]
Looks like date time zone data is changed (https://www.joda.org/joda-time/changes-report.html). Should it be reflected here as well?

**Comment by dlew** [comment]
joda-time-android [already has 2019a tzdata](https://github.com/dlew/joda-time-android/blob/master/CHANGELOG.md#21012-2019-03-28). If you want to upgrade to joda-time 2.10.2 early you can just include that as a dependency in addition to joda-time-android (just make sure to use the no-tzdb artifact so you don't include tzdata resources you never end up using; that just inflates your APK size).

**Comment by emartynov** [comment]
Thank you! We already doing it and I forgot that this library incorporates time zone changes much faster than joda time.
