### ISSUE TITLE
PeriodFormat string resources are in ISO 8859-1 encoding instead of UTF-8

### ISSUE THREAD

**Issue by elFua** [dlew/joda-time-android#23]
### Description
The resource bundle strings for PeriodFormat (and possibly others) are using ISO Latin-1 encoding instead of UTF-8.

For example this file is not UTF-8 encoded (actual encoding ISO 8859-1):

https://github.com/dlew/joda-time-android/blob/master/library/src/org/joda/time/format/messages_es.properties.

NOTE: *github shows it without problems because it detects it correctly as _ISO-8859-1_*.

These files have incorrect encoding:

    messages_es.properties
    messages_fr.properties
    messages_da.properties
    messages_pt.properties

### Actual result
Strings render in android apps with broken accented characters.

### Expected result
Accented characters are displayed correctly.

### Suggested solution
Re-encode the `.properties` to UTF-8 or to Unicode escapes.

Example using `iconv`:

    iconv -f ISO-8859-1 -t UTF-8 messages_es.properties > messages_es_UTF8.properties

**Comment by dlew** [comment]
Interesting. Would it make more sense to submit this issue to the core https://github.com/JodaOrg/joda-time project, since that's where those files come from?

**Comment by dlew** [comment]
joda-time-android now entirely depends on joda-time, which is where those files are located; I suggest re-submitting to that project.

**Comment by dlew** [comment]
Closing now that this is in https://github.com/JodaOrg/joda-time/issues/228

**Comment by elFua** [comment]
Opened upstream bug: https://github.com/JodaOrg/joda-time/issues/228
