### ISSUE TITLE
getRelativeTimeSpanString enhancement

### ISSUE THREAD

**Issue by janbolat** [dlew/joda-time-android#230]
Hi,

currently `getRelativeTimeSpanString` method returns relative timespan to `DateTime.now()`. What do you think of extending it where you could get `getRelativeTimeSpanString` relative to some another `DateTime`? 

Thank you

**Comment by dlew** [comment]
This library is kind of in maintenance mode, so I'm hesitant to add any new APIs. And one can do the math to make any time relative to `now()` (or at least within a few milliseconds).

**Comment by dlew** [comment]
Closing because we're not adding a new API method at this time.
