### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by anthony3444** [dlew/joda-time-android#239]
Hi guys!

An user had a crash this morning (samsung Galaxy S7, Android  7.0):

> Fatal Exception: java.lang.NoSuchMethodError
> No direct method ()B in class B or its super classes (declaration of 'byte' appears in generated class)
> org.joda.time.UTCDateTimeZone.<init>

```
org.joda.time.UTCDateTimeZone.<init> (UTCDateTimeZone.java:30)
org.joda.time.UTCDateTimeZone.<clinit> (UTCDateTimeZone.java:26)
org.joda.time.DateTimeZone.<clinit> (DateTimeZone.java:108)
net.danlew.android.joda.ResourceZoneInfoProvider.loadZoneInfoMap (ResourceZoneInfoProvider.java:174)
net.danlew.android.joda.ResourceZoneInfoProvider.<init> (ResourceZoneInfoProvider.java:38)
net.danlew.android.joda.JodaTimeAndroid.init (JodaTimeAndroid.java:39)
com.xxxx.MyApplication.setupApplication (MyApplication.java:138)
```

In my proguard file, I have:

-dontwarn org.joda.convert.**
-dontwarn org.joda.time.**
-keep class org.joda.time.** { *; }
-keep interface org.joda.time.** { *; }

Thank you very much for your great work!

**Comment by dlew** [comment]
I don't really know what to make of this! Have you checked the actual APK to see if the method is in it?

**Comment by dlew** [comment]
Closing for lack of reproduction. If you have a repro, I'd be happy to look into it more.
