### ISSUE TITLE
joda security issues

### ISSUE THREAD

**Issue by abunur** [dlew/joda-time-android#240]
This is coming up in two places in the library, when scanned with Veracode's security tools. Basically there's a vulnerability with logging, where the logs need to be sanitized properly.
Details from the scan:

**CRLF Injection**
Description
The acronym CRLF stands for "Carriage Return, Line Feed" and refers to the sequence of characters used to denote the end of a line of text. CRLF injection vulnerabilities occur when data enters an application from an untrusted source and is not properly validated before being used. For example, if an attacker is able to inject a CRLF into a log file, he could append falsified log entries, thereby misleading administrators or cover traces of the attack. If an attacker is able to inject CRLFs into an HTTP response header, he can use this ability to carry out other attacks such as cache poisoning. CRLF vulnerabilities primarily affect data integrity.
Recommendations
Apply robust input filtering for all user-supplied data, using centralized data validation routines when possible. Use output filters to sanitize all output derived from user-supplied input, replacing non-alphanumeric characters with their HTML entity equivalents.

**Associated Flaws by CWE ID:**
Improper Output Neutralization for Logs CWE ID 117 

Description
A function call could result in a log forging attack. Writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files. Corrupted log files can be used to cover an attacker's tracks or as a delivery mechanism for an attack on a log viewing or processing utility. For example, if a web administrator uses a browser-based utility to review logs, a cross-site scripting attack might be possible.
Recommendations
Avoid directly embedding user input in log files when possible. Sanitize untrusted data used to construct log entries by using a safe logging mechanism such as the OWASP ESAPI Logger, which will automatically remove unexpected carriage returns and line feeds and can be configured to use HTML entity encoding for non-alphanumeric data. Only write custom blacklisting code when absolutely necessary. Always validate untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible.

**Instances found via Static Scan**

net/danlew/android/joda/TimeZoneChangedReceiver.java 24
.../TimeZoneChangedReceiver.java 27

**Comment by dlew** [comment]
I'm not a big fan of automated scans. If you can show me how someone will actually use joda-time-android as an attack vector then I'll consider fixing.
