### ISSUE TITLE
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" 

### ISSUE THREAD

**Issue by Jomme5** [dlew/joda-time-android#241]
Got this error when executing:
`DateTime.now().toLocalTime().toString()`

I did initialization:
`JodaTimeAndroid.init(this);`

**Comment by Jomme5** [comment]
The initialization happend in MainActivity.java

The actual toLocalTime-call happened in a an interval worker-class(possibly another thread).
I copied the initialization to the worker-class like:
`JodaTimeAndroid.init(getApplicationContext()`
which then works. 
So you have to do an initialization in every class or every worker-thread?

**Comment by dlew** [comment]
It should be valid for the entire application context.

Is it possible that your worker is in another process? In that case you would run into trouble.

**Comment by Jomme5** [comment]
I would also think that `JodaTimeAndroid.init(this);` is for the entire app-context.

I actually make use of PeriodicWorkRequest, witch needs a workerclass. So, it does run in the same application, but maybe on a different thread. However, I'm in doubt about that, since PeriodicWorkRequest makes use of the Workmanager-service. And so the worker-class is maybe called from another system process.

I also tried with `JodaTimeAndroid.init(getApplicationContext())` in MainActivity, in stead of `JodaTimeAndroid.init(this)` but got the same results.

**Comment by dlew** [comment]
Threading should make no difference on whether this works or not.

If you have a sample app showing the problem, I could dig into it. The basic idea, though, is that we need to provide the `Context` to the timezone provider. If you're in some sandboxed situation, then the first initialization won't reach there.

**Comment by dlew** [comment]
Closing for lack of reproduction. If you have a repro, I'd be happy to look into it more.
