### ISSUE TITLE
Programmatically determine tzdata version in use?

### ISSUE THREAD

**Issue by StringMon** [dlew/joda-time-android#242]
Is there any facility in JodaTimeAndroid for retrieving the version of tzdata that the library was built with?

If not, this is certainly a feature I'd like to see. With a small nudge in the right direction, I'd be happy to create a pull request for it.

Thanks!

**Comment by dlew** [comment]
There isn't, but I'm open to adding a constant that defines it.

What sort of format would you expect it to be in? If it were just the name (e.g. "2019c"), then that might make it hard to compare to other versions, but I'm not sure what other scheme would work. Maybe just use that label and force people to do lexicographical ordering?

**Comment by StringMon** [comment]
I'd advocate for using just the tzdb release name ("2019c"), as that's the upstream standard. The issue of sorting has been discussed on the tz mailing list (example: https://mm.icann.org/pipermail/tz/2019-May/027937.html), and the current naming convention is designed for lexicographical comparison to work.

**Comment by dlew** [comment]
Sounds good to me.

If you want to open a PR, I'd probably just add a String constant to `JodaTimeAndroid` and call it at that.
