### ISSUE TITLE
NotSerializableException thrown when using Proguard/R8

### ISSUE THREAD

**Issue by ntsik** [dlew/joda-time-android#254]
[Joda classes use the `writeObject` special method](https://github.com/JodaOrg/joda-time/search?q=writeobject&unscoped_q=writeobject) to enable [`Serializable`](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html). In order to keep the `writeObject` method, [Proguard and R8 require rules to be added specifically for `Serializable`](https://www.guardsquare.com/en/products/proguard/manual/examples#serializable).

These `Serializable` rules are not provided by the [default Android rules](https://cs.android.com/android/platform/superproject/+/master:tools/base/files/proguard-android.txt?q=proguard-android.txt&ss=android) or by the [current rules for this library](https://github.com/dlew/joda-time-android/blob/bd1369bfebda7051d6ee41080129a5cfa23ea626/library/proguard-rules.txt). Thus, on a build with Proguard/R8 enabled, serializing Joda classes will result in a `NotSerializableException` due to `writeObject` being removed and default serialization being used.

To fix this, `Serializable` rules should be added to the consumer rules for this library.

(Related issue: https://github.com/dlew/joda-time-android/issues/253)

**Comment by dlew** [comment]
If you want to submit a PR I'd welcome it. Otherwise I probably won't get around to this until the next time tzdata updates.

(I don't really consider `Serializable` support a super high priority because `Serializable` on Android is awful and slow.)

**Comment by EBfVince** [comment]
Thank you @ntsik ! Your fix works perfectly.
I hope they will merge your PR.

**Comment by dlew** [comment]
I approved the PR, I can merge it as well.

I'll push out a new version later this week.
