### ISSUE TITLE
Timezone not always being converted properly

### ISSUE THREAD

**Issue by riclage** [dlew/joda-time-android#27]
I have encounter a new issue related to timezones. In at least one of them, the conversion is not working properly. Try this DateTime object:

`new DateTime(DateTimeZone.forID("Asia/Dhaka"))`

For me it returns a DateTime with GMT+7 timezone when it should have been +6 (as per the timezone data file). I'm trying to find out where the problem is and will let you if I find out.

Thanks.
Edit: If I don't use your library but just the latest DateTime library instead, the timezone gets parsed correctly.

**Comment by riclage** [comment]
So here is the solution: you need to update the ZoneInfoCompiler with the latest from the [official lib](https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/tz/ZoneInfoCompiler.java). Note how the latest commit there was precisely to address the "Asia/Dhaka" timezone.

**Comment by dlew** [comment]
I think the real solution is to use joda-time's `ZoneInfoCompiler`, then use a gradle task to rename the output. Then I don't have to worry about maintaining another version.

I'm going to be out of town for a week but I'll check this out when I get back.

**Comment by dlew** [comment]
Fixed as of 3d801213a05e92ef18246e178c313932c489fe5a

**Comment by dlew** [comment]
joda-time-android 2.7.1 has been pushed to maven central and should show up in a few hours.
