### ISSUE TITLE
in Range of

### ISSUE THREAD

**Issue by dadou181295** [dlew/joda-time-android#271]
Hey, trying to create a function to check  a given string time HH:mm is in range of another comparing to Now

(Example:  if  currentHour is between 12:35 and 15:00 return true)

```
 fun isTimeInRange(before: String, after: String): Boolean {


        val now = DateTime.now()
        val format = DateTimeFormat.forPattern("HH:mm")
        
        return now >= DateTime.parse(before,format) && now <= DateTime.parse(after,format)


    }
```

Please where I'm wrong?

**Comment by dlew** [comment]
The issue tracker is for bug reports and feature requests. Please save usage questions for Q&A sites like [StackOverflow](https://stackoverflow.com/).
