### ISSUE TITLE
integration of tz data in joda-time-android

### ISSUE THREAD

**Issue by TedaLIEz** [dlew/joda-time-android#286]
I managed to import joda-time-android library and found is way faster than joda-time to load the tz database into memory. But I found joda-time-android library load the tz data in readable format, whereas joda-time load the tz database in some other format. How do I verify that joda-time-android has the same timezone data comparing with joda-time?

**Comment by dlew** [comment]
The two projects use the same tzdata; it's just that joda-time checks in the compiled version of the tzdata, whereas I felt like it was better to compile the tzdata as part of joda-time-android's build process.

[You can see here](https://github.com/dlew/joda-time-android/blob/main/buildSrc/src/main/groovy/net/danlew/android/joda/CompileTzDataTask.groovy#L45-L46) that during joda-time-android's builds, we use the joda-time `ZoneInfoCompiler` to compile the tzdata into joda-time's format.

**Comment by TedaLIEz** [comment]
Cool, it makes sense to me. Thx for your help and this library 👍
