### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by Louiswang86** [dlew/joda-time-android#305]
Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer need
ed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'ctest'

**Comment by dlew** [comment]
See https://github.com/dlew/joda-time-android/issues/303#issuecomment-1172957862 for a fix.
