### ISSUE TITLE
Could not find joda-time-2.11.0-no-tzdb (v.2.11.0)

### ISSUE THREAD

**Issue by el-qq** [dlew/joda-time-android#312]
### Summary

Using version 2.10.14 - ok, app build
with 2.11.0 an error occurs

```
dependencies
   ...
   api 'net.danlew:android.joda:2.11.0'
```

### Error

```
> Could not resolve all files for configuration ':app:genericDebugRuntimeClasspath'.
   > Failed to transform joda-time-2.11.0-no-tzdb (joda-time:joda-time:2.11.0) to match attributes {artifactType=android-jni, org.gradle.status=release}.
      > Could not find joda-time-2.11.0-no-tzdb (joda-time:joda-time:2.11.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/joda-time/joda-time/2.11.0/joda-time-2.11.0-no-tzdb
```

**Comment by dlew** [comment]
Hmm, it looks like it's in maven central: https://repo1.maven.org/maven2/joda-time/joda-time/2.11.0/

Not sure what's going on but it's some configuration problem on your end - are you including `mavenCentral()` as a repository?

**Comment by el-qq** [comment]
> including mavenCentral() as a repository

Yes. mavenCentral() is has been added to the entire project  👀

**Comment by dlew** [comment]
I believe I've tracked down the issue to something with the artifact selector setup. Will try to publish a new release tonight for y'all.

**Comment by el-qq** [comment]
Thanks. Its working
