### ISSUE TITLE
The datetime zone id 'Asia/Kolkata' is not recognised

### ISSUE THREAD

**Issue by nikhilAgarwalM** [dlew/joda-time-android#316]
I am using Joda android library 
implementation "net.danlew:android.joda:$joda_version"
joda_version = '2.11.0.1'

I am getting following crash - 
```
2022-09-02 17:03:40.134 2546-2546/com.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.debug, PID: 2546
    java.lang.IllegalArgumentException: The datetime zone id 'Asia/Kolkata' is not recognised
        at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:398)
        at com.app.base.utils.DateTimeUtils.isLaterThanNow(DateTimeUtils.kt:64)
```
When I am calling  `DateTimeZone.forID("Asia/Kolkata")` in my code

The same issue is not being produced with 
joda_version = '2.10.7.2' with `JodaTimeAndroid.init(context)`

**Comment by dlew** [comment]
Two questions...

1. Can you verify that [App Startup](https://developer.android.com/topic/libraries/app-startup) is running properly? (This has been how the library initializes itself since 2.10.9.)

2. Does it work for any timezones whatsoever (e.g. try "america/chicago", "europe/paris")?

**Comment by dlew** [comment]
Closing due to lack of follow-up.
