### ISSUE TITLE
Can't find referenced class org.joda.time.tz.ZoneInfoCompiler

### ISSUE THREAD

**Issue by sjvc** [dlew/joda-time-android#32]
Hi! I've added joda time to my project as a dependency:

dependencies {
    compile 'net.danlew:android.joda:2.7.0'
}

But when generating a signed APK, Android Studio shows this warning: "Warning:org.joda.time.tz.DateTimeZoneBuilder$PrecalculatedZone: can't find referenced class org.joda.time.tz.ZoneInfoCompiler"

Should I ignore it adding a "-dontwarn" in proguard?

**Comment by dlew** [comment]
I would ignore that; `DateTimeZoneBuilder` isn't used at all (except to generate the tz rules at build time).

I wonder why it can't find `ZoneInfoCompiler`, though... should be included in the JAR too.

**Comment by sjvc** [comment]
Ok, thanks, I added the rule to proguard.

If I'm using gradle, it's enough using "compile 'net.danlew:android.joda:2.7.0'" or do I need to include the joda-time jar?

**Comment by dlew** [comment]
That's all you need; joda-time is a dependency of joda-time-android, so it'll automatically be pulled into the project.

**Comment by sjvc** [comment]
Ok. Thank you Daniel!
