### ISSUE TITLE
When i added: compile 'net.danlew:android.joda:2.7.0' in build.gradle(app) i am unable to compile

### ISSUE THREAD

**Issue by HenryTimelessness** [dlew/joda-time-android#33]
Error:(52, 13) Failed to resolve: net.danlew:android.joda:2.7.0

**Comment by dlew** [comment]
Did you make sure to add 

    repositories {
      mavenCentral()
    }

Anywhere in the build.gradle file?

**Comment by HenryTimelessness** [comment]
It seemed that there was some syncing issues in android studio. Unchecking the option to work in offline mode and retrying a few more times allowed me to successfully resolve the dependency. Thanks!
