### ISSUE TITLE
tzdb 2024a 

### ISSUE THREAD

**Issue by janbolat** [dlew/joda-time-android#342]
Hello,

would it be possible for you to kindly update the tzdb version to 2024a?

Thank you

https://data.iana.org/time-zones/tzdb/NEWS

**Comment by dlew** [comment]
joda-time-android uses the [global-tz](https://github.com/JodaOrg/global-tz) version of tzdata; once that updates I'll push out an update here.

**Comment by dlew** [comment]
Resolved and released: https://github.com/dlew/joda-time-android/pull/344
