### ISSUE TITLE
Issue with getNameKey returning "%z" for certain timezones in v2.13.0

### ISSUE THREAD

**Issue by Jaquelineds** [dlew/joda-time-android#351]
Hello,

I've encountered an issue in the release v2.13.0 with the getNameKey function when fetching certain timezones. Specifically, for the following timezones:
Gulf Standard Time
Vietnam (UTC +7)
Singapore (UTC +8)

The function getNameKey is returning "%z" instead of the expected name key. This issue does not occur in the previous release (v2.12.7), where the function works as expected.

I hope this can be addressed in a future release.

Thank you!

**Comment by dlew** [comment]
This is likely to be an issue with the base [joda-time](https://github.com/JodaOrg/joda-time), not the Android-specific variant (which builds on top of it). Could you check to see if the same behavior happens when using *just* joda-time (not the Android version)?

**Comment by Jaquelineds** [comment]
You're right, the issue is not related to the Android library. I performed some tests and have opened an issue in the Joda-Time repository, so I'll close this issue. Thank you for your quick response!
