### ISSUE TITLE
can't find referenced class org.joda.time.tz.ZoneInfoCompiler

### ISSUE THREAD

**Issue by saduino** [dlew/joda-time-android#36]
I can't generate a apk with proguard active, I always get the following warning: 

Warning:org.joda.time.tz.DateTimeZoneBuilder$PrecalculatedZone: can't find referenced class org.joda.time.tz.ZoneInfoCompiler

I know I could add -dontwarn org.joda.time.tz.**, but then the app crashes when I call JodaTimeAndroid.init(this);

@Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        setContentView(R.layout.activity_main);
        JodaTimeAndroid.init(this);
}

I'm using Android Studio

the exception I get when I use -dontwarn:

02-22 12:57:16.237    6971-6971/? E/JodaTimeAndroid﹕ Failed to retrieve identifier: type=class net.danlew.android.joda.R$raw name=__tzdata_zoneinfomap
    java.lang.NoSuchFieldException: __tzdata_zoneinfomap
            at java.lang.Class.getField(Class.java:1048)
            at net.danlew.android.joda.ResUtils.getIdentifier(ResUtils.java:105)
            at net.danlew.android.joda.ResourceZoneInfoProvider.openResource(ResourceZoneInfoProvider.java:114)
            at net.danlew.android.joda.ResourceZoneInfoProvider.<init>(ResourceZoneInfoProvider.java:39)
            at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:39)
            at com.newApp.MainActivity.onCreate(MainActivity.java:158)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
02-22 12:57:16.239    6971-6971/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.newApp, PID: 6971
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newApp/com.newApp.MainActivity}: java.lang.RuntimeException: Could not read ZoneInfoMap
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.RuntimeException: Could not read ZoneInfoMap
            at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:42)
            at com.newApp.MainActivity.onCreate(MainActivity.java:158)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by saduino** [comment]
I somewhat solved it, not a very nice solution, but it seems to work

I downloaded the joda-time-2.7.jar and included: -libraryjars libs/joda-time/joda-time-2.7.jar into the proguard-rules.pro

still I can't write JodaTimeAndroid.init(this); how it is adviced here (https://github.com/dlew/joda-time-android#usage), but the app seems to work how it should and it doesn't crash anymore.


But I'm sill interested in the way to solve this problem without such a hack.

**Comment by dlew** [comment]
It looks like you're only including the JAR, not the AAR, of this library. There are resources that are needed in the AAR for this library to work. What is in your build.gradle?

**Comment by saduino** [comment]
dependencies {
    compile 'net.danlew:android.joda:2.7.1'
}

this is in my build.gradle

**Comment by dlew** [comment]
Hmm... without knowing more it's hard to help. But it should be pulling in the AAR file that includes `__tzdata_zoneinfomap`. Maybe it's being stripped out in another build step? Like some minifying?

**Comment by tigerpenguin** [comment]
I am using proguard to minify but I'm not seeing the issue. Not sure if this will help, but here's my build.gradle and proguard settings:
```
compile 'net.danlew:android.joda:2.7.1'
compile('com.fasterxml.jackson.datatype:jackson-datatype-joda:2.4.4') {
    exclude module: 'joda-time'
}
compile 'org.joda:joda-convert:1.7'
```

```
-dontwarn javax.xml.bind.DatatypeConverter
-dontwarn org.joda.time.tz.ZoneInfoCompiler
```

I have some extra stuff as I am using jackson databind.

**Comment by Narthe** [comment]
Same issue here, used maven option, this is my build.gradle :
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.2'
    compile 'net.danlew:android.joda:2.7.1'
}

**Comment by dlew** [comment]
I've got some good news and some bad news. The next version of joda-time should fix this issue. The bad news is that you'll probably run into unavoidable ProGuard issues at that point. :p

I'll just have to come up with some ProGuard details on the README I think.

**Comment by tigerpenguin** [comment]
> I'll just have to come up with some ProGuard details on the README I think.

^ This is great. I wish all open source Android projects had this (and closed-source commercial third party libraries should definitely have it). Thank you.

**Comment by brsengar** [comment]
Hi
Any idea when this would be fixed. I have similar issues in my project.
Thanks

**Comment by dlew** [comment]
Not really - it'll depend on the underlying joda-time dependency updating.

**Comment by vovkab** [comment]
Try this proguard config:

```
# Joda Time
-dontwarn org.joda.convert.**
-dontwarn org.joda.time.**
-keep class org.joda.time.** { *; }
-keep interface org.joda.time.** { *; }
```

**Comment by squeeish** [comment]
Does @vovkab's solution work for anybody? It doesn't work for me.

**Comment by Splaktar** [comment]
Yes, the Proguard snippet [here](https://github.com/krschultz/android-proguard-snippets/blob/master/libraries/proguard-joda-time.pro) fixed this for me. Thank you!

**Comment by squeeish** [comment]
Yeap that's what I meant, building is fine but the app crashes still. I'm pretty new to Proguard and all this obsfucating stuff. Could anyone shed more light on this matter?

**Comment by dlew** [comment]
Are you doing Eclipse builds or Gradle builds?

**Comment by squeeish** [comment]
@dlew Gradle :)

**Comment by dlew** [comment]
A combination of joda-time 2.8 and properly including joda-convert should fix all proguard issues (at least, they do on my end).

**Comment by Splaktar** [comment]
So I need to add `compile 'org.joda:joda-convert:1.2'` to my app to get it to stop crashing with joda-time-android 2.8? I tried just using `compile 'net.danlew:android.joda:2.8.0'` but it still crashes on some user's phones.

**Comment by dlew** [comment]
@Splaktar No, you shouldn't need to include it. My comment is slightly out-of-date. You either need to proguard, or you need to include joda-convert.

Those crashes have nothing to do with this issue. I've looked into it and I honestly have no idea how that's happening, especially since it works fine on most phones.

**Comment by Splaktar** [comment]
Yep, it is really puzzling. It works on my Nexus 5 just fine, but another customer's Nexus 5 crashes the app every time I try to go to joda-time-android 2.7.1 or above :( I'm using Proguard, so I'll remove the temporary joda-convert include, thank you.

**Comment by ligi** [comment]
I just ran into the problem with 'net.danlew:android.joda:2.9.2' after several gradle clean assemble -> Install runs

**Comment by dlew** [comment]
@ligi Does it happen on any older builds?

**Comment by ligi** [comment]
I just activated proguard on this project (
https://github.com/ligi/PassAndroid )

**Comment by dlew** [comment]
I'm not seeing this problem when building your project. The problem I see w/ proguard is this:

```
Warning: com.squareup.leakcanary.DisplayLeakService: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
```

Which I actually happened to fix in LeakCanary, but it hasn't been released yet: https://github.com/square/leakcanary/pull/308

**Comment by ligi** [comment]
When I start the app build with the latest master I get:
```
02-18 19:21:17.953  1559 30180 I ActivityManager: Start proc 4226:org.ligi.passandroid/u0a68 for activity org.ligi.passandroid/.ui.PassListActivity
02-18 19:21:17.991  4226  4226 W System  : ClassLoader referenced unknown path: /data/app/org.ligi.passandroid-1/lib/x86_64
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: Failed to retrieve identifier: type=class net.danlew.android.joda.R$raw name=joda_zoneinfomap
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: java.lang.NoSuchFieldException: joda_zoneinfomap
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at java.lang.Class.getField(Class.java:891)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at net.danlew.android.joda.ResUtils.a(SourceFile:105)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at net.danlew.android.joda.ResourceZoneInfoProvider.b(SourceFile:114)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at net.danlew.android.joda.ResourceZoneInfoProvider.<init>(SourceFile:39)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at net.danlew.android.joda.JodaTimeAndroid.a(SourceFile:39)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at org.ligi.passandroid.App.onCreate(SourceFile:27)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at android.os.Looper.loop(Looper.java:148)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at java.lang.reflect.Method.invoke(Native Method)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-18 19:21:17.995  4226  4226 E JodaTimeAndroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-18 19:21:17.996  4226  4226 D AndroidRuntime: Shutting down VM
02-18 19:21:17.996  4226  4226 E AndroidRuntime: FATAL EXCEPTION: main
02-18 19:21:17.996  4226  4226 E AndroidRuntime: Process: org.ligi.passandroid, PID: 4226
02-18 19:21:17.996  4226  4226 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.ligi.passandroid.App: java.lang.RuntimeException: Could not read ZoneInfoMap
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: Caused by: java.lang.RuntimeException: Could not read ZoneInfoMap
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at net.danlew.android.joda.JodaTimeAndroid.a(SourceFile:42)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at org.ligi.passandroid.App.onCreate(SourceFile:27)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
02-18 19:21:17.996  4226  4226 E AndroidRuntime: 	... 8 more
02-18 19:21:17.996  1559 30347 W ActivityManager:   Force finishing activity org.ligi.passandroid/.ui.PassListActivity

```

leak-canary is no-op for release - these stubs should not make any problem with proguard - but I will care for this when there is a problem and I overcome the joda-time crash
    
`releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'`

**Comment by dlew** [comment]
Ah, I've figured it out. Your proguard is removing stuff from your `R`. It just happens that joda-time-android is the first part of your app trying to access it.

You should really use the default proguard file Android comes with in addition to your own. It handles stuff like this:

    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'

**Comment by ligi** [comment]
thanks!
