### ISSUE TITLE
Time Zone crash

### ISSUE THREAD

**Issue by tasomaniac** [dlew/joda-time-android#38]
I am getting this crash with version 2.7.1

> java.lang.IllegalArgumentException: The datetime zone id 'Africa/Abidjan' is not recognised

What should I do? It is really confusing. It is working normally with the original joda-time library. Should I checkout this repo and get timezones myself?

**Comment by dlew** [comment]
Did you make sure to call `JodaTimeAndroid.init()` at some point?

Check out usage: https://github.com/dlew/joda-time-android#usage

**Comment by tasomaniac** [comment]
Oh really really sorry. It is a really basic mistake.

But somehow even I saw that part, I just copied Gradle dependency line and
directly went to Android Studio. Maybe you should write this initialization
before that.

**Comment by dlew** [comment]
Hmm, I'll consider it in the future.

In the past we just... blew up if you didn't call it. Now it doesn't give a clear error message.
