### ISSUE TITLE
Possible race condition between joda-time-android, Ion, and GSON

### ISSUE THREAD

**Issue by jondwillis** [dlew/joda-time-android#39]
I recently switched from joda-time to use joda-time-android and ran into a strange race condition that I'd like to understand. This issue manifests, I think, due to my use of Ion (https://github.com/koush/ion), set up to use a custom GSON (https://code.google.com/p/google-gson/) for serialization and deserialization. It doesn't manifest when I use vanilla joda-time, which unfortunately uses more memory and tends to block the main thread for longer as it bootstraps.

In my `Application` subclass, I set up JodaTimeAndroid, GSON, and configure Ion to use the custom `Gson` instance to serialize/deserialize `DateTime`:

    @Override
    public void onCreate() {
        ...

        super.onCreate();

        JodaTimeAndroid.init(this);
       
        ...
 
        Gson gson = new GsonBuilder()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
                .setLongSerializationPolicy(LongSerializationPolicy.DEFAULT)
                .registerTypeAdapter(DateTime.class, new DateTimeDeserializer())
                .registerTypeAdapter(DateTime.class, new DateTimeSerializer())
                .create();

        Ion.getDefault(this).configure().setGson(gson);
    }

    ...

    private static class DateTimeSerializer implements JsonSerializer<DateTime> {
        public JsonElement serialize(DateTime src, Type typeOfSrc, JsonSerializationContext context) {
            return new JsonPrimitive(src.toString());
        }
    }

    private static class DateTimeDeserializer implements JsonDeserializer<DateTime> {
        public DateTime deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context)
                throws JsonParseException {
            return new DateTime(json.getAsJsonPrimitive().getAsString());
        }
    }

Some short time later, I make a network call with Ion in a `Service`, serializing into a POJO model that has a DateTime field. It also happens to be wrapped in an RxJava `Observable` run on the IO scheduler:
    
                                            Observable.from(
                                                    Ion.with(this)
                                                            .load(uri)
                                                            .as(ChannelTimelineMap.class),
                                                    Schedulers.io()))

One out of every few restarts of the `Application`, GSON throws an error, saying it can't parse a string timetamp into my DateTime object. I know there's a lot of interplay between libraries here, but also thought you'd have insight since you work with a lot of them already and, y'know, wrote this library ;)

Also I'm a huge fan, thanks for all the fantastic work and writing you've done!

**Comment by dlew** [comment]
Hmm, I am not sure what's going on given that it's only failing once in a while. Could you paste the exact error?

In general, you should avoid any instantiation of `DateTime` objects before calling `JodaTimeAndroid.init()`. If there's some method being called beforehand (like a static initializer) then that could be the culprit for why it's not working so well.

**Comment by jondwillis** [comment]
@dlew I suspected that as well and removed static references to DateTime. This turned out to be a separate issue with Ion though.
