### ISSUE TITLE
JodaTimeAndroid is null after screen rotation

### ISSUE THREAD

**Issue by firetrap** [dlew/joda-time-android#40]
Declared JodaTimeAndroid.init(this); in public class BLABLAApplication extends Application {@Override
    public void onCreate() {
        super.onCreate();
        NetworkHelper.getInstance().initialize(this);
        BusHelper.post(new InitializeAction());
        JodaTimeAndroid.init(this);
    }}

but after device rotation the objects are null, is JodaTimeAndroid a Singleton?!

**Comment by dlew** [comment]
"The objects" being what exactly?

And yes, JodaTimeAndroid is a singleton.

**Comment by firetrap** [comment]
Sorry i've checked your source and everything is at it should, it was a bug in another lib which is using JodaTimeAndroid who tricked me.

Sorry and sincere apologies for opening an issue without any issue at all ;)

**Comment by dlew** [comment]
No problem, have a nice day.
