### ISSUE TITLE
Does anyone still use joda-time-android as an Eclipse library?

### ISSUE THREAD

**Issue by dlew** [dlew/joda-time-android#41]
I'm thinking of abandoning support for the old-style library setup. It will make building the project easier.

I'm wondering if anyone can present a compelling case for why I should *not* completely switch to a Gradle-based system.

**Comment by AndwareSsj** [comment]
I also use eclipse

**Comment by yjukaku** [comment]
So do I :+1:

**Comment by dlew** [comment]
Given that I asked this two months ago and got a grand total of two replies, I'm going to say that supporting Eclipse going forward is probably not in the cards.

There are a few advantages to switching solely to Gradle-based system:

- Single path of execution is simpler to manage.
- Can depend solely on Gradle-based features (like dependency on joda-time).
- Don't need to check in compiled version of tzdata into repo anymore.

On top of that, there's no reason older versions of joda-time-android wouldn't keep working going forwards for Eclipse. As a result, I think 2.8.1 will be the final version supporting Eclipse.

**Comment by pimato** [comment]
good decision, and thanks for the good work :+1:
