### ISSUE TITLE
DateTimeZone.getDefault() sometimes return right value, sometimes return utc

### ISSUE THREAD

**Issue by josefrvaldes** [dlew/joda-time-android#45]
This is exactly what happens to me. I have your last version installed.
I tried using "JodaTimeAndroid.init(this);" in the onCreate of the first activity on my app. As it sometimes failed, then I put it in the onCreate of the activity where I use Joda mostly, and as it still fails, now I put it in the onResume of the activity i use Joda mostly.. 

But it's still not working..

Any suggestion??

My current timezone is "Europe/Dublin".

BTW: I don't use setDefaultTimeZone at all.

EDIT: it's not a problem that there is no timezones available because after retrieve my current timezone, I show my available timezones and I have 583..

**Comment by dlew** [comment]
Have you tried putting it in `Application`? Then it most likely run before any code that actually uses it.

**Comment by josefrvaldes** [comment]
I've made some changes and I've been the whole morning without issues.. But one of the changes I did was to downgrade from 2.7.2 to 2.7.1.

I can't really afirm that it have been the downgrade what have fix the problem because I made several changes, but what I'll do is to go back to 2.7.2 and see if the error happens again, and then, I will let you know.. ok?

Thank you very much for your work!

**Comment by dlew** [comment]
The only change between 2.7.1 and 2.7.2 was updating the timezone database, so I doubt that had anything to do with it.

**Comment by josefrvaldes** [comment]
Ok, I will upgrade then to the last version and I will let you know if it crashes again.

**Comment by josefrvaldes** [comment]
Ok, I've been testing it for several days and it haven't failed again, so I think it was my fault because I was doing something wrong or something. I will close this issue now.

Thank you very much for your help!
