### ISSUE TITLE
mergeResources error with Android Gradle plugin 1.3

### ISSUE THREAD

**Issue by rafaeltoledo** [dlew/joda-time-android#46]
After upgrading to plugin 1.3.0-beta1, I'm receiving an error:

```
Error:Execution failed for task ':app:mergeDebugResources'.
> /<path to my project>/app/build/intermediates/exploded-aar/net.danlew/android.joda/2.7.2/res/raw/__tzdata_africa_abidjan: Error: File-based resource names must start with a lowercase letter
```

Need to check if this will be fixed on next releases of the plugin or the library needs to be fixed.

**Comment by jlelse** [comment]
Same problem here

**Comment by rhinon** [comment]
I'm semi-trapped by this as I'm trying to integrate the new google services for GCM and it's forcing me to use gradle 1.3 (https://developers.google.com/cloud-messaging/android/client).

Wish the old docs for gcm were still up.

**Comment by dlew** [comment]
I'm busy with IO but I'll be working on a release soon.
