### ISSUE TITLE
Version 2.8.0 not available in Maven Central

### ISSUE THREAD

**Issue by mdpearce** [dlew/joda-time-android#55]
Version 2.8.0, listed as the current version in the README will not download and compile in from mavencentral.

I notice that it has only just gone live, so perhaps it's just a caching/timing issue - in which case ignore this - but I thought I'd bring it up just in case something went wrong with the push.

**Comment by dlew** [comment]
It hasn't gone live yet; I was going to push soon but got held up by a build bug.

I'm rolling back the README until it goes live.
