### ISSUE TITLE
NoClassDefFoundError net.danlew.android.joda.R$raw

### ISSUE THREAD

**Issue by SoAddicted** [dlew/joda-time-android#69]
Hi, 
I get the following error when I launch my application on a KitKat (4.4.4) Device.

`java.lang.NoClassDefFoundError: net.danlew.android.joda.R$raw`

on a 5.0 or 5.1 device everything works fine.

I use the latest version

`compile 'net.danlew:android.joda:2.8.1'`

with ProGuard

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

**Comment by dlew** [comment]
What happens if you don't have proguard enabled?

**Comment by SoAddicted** [comment]
The same actually, I use `JodaTimeAndroid.init(this);` in onCreate of my Application extending Class.
Any ideas?

**Comment by SoAddicted** [comment]
Okay i got it, I had to add `multiDexEnabled true` and only tested on Lollipop Devices, when using multiDex on  pre 5.0 you have to add `compile 'com.android.support:multidex:1.0.0'` and make your Application class extend MultiDexApplication.

I'm kinda curious why thats not shown in any of the logs, but because of the limit, every external library over the limit wasn't working anymore.

Thanks
