### ISSUE TITLE
Maven artifact add joda-time in two versions and don't provide android.joda jar

### ISSUE THREAD

**Issue by KrzychuJedi** [dlew/joda-time-android#79]
I add maven dependency to my project pom (lib version 2.8.1):
        <dependency>
            <groupId>net.danlew</groupId>
            <artifactId>android.joda</artifactId>
            <version>${android.version}</version>
        </dependency>

And maven download joda-time:2.6 and joda-time:no-tzdb:2.8.1
android.joda is not downloaded at all.
Is everything fine with android.joda pom?

**Comment by dlew** [comment]
Could you be a bit more specific with how you're using the library? What exact syntax are you using?

**Comment by KrzychuJedi** [comment]
I didn't notice that github remove all brackets from my post... I use standard maven syntax. I just add dependency to pom same as others libraries. I use intellij with maven integration and it show me that he add to libaries  joda-time:2.6 and joda-time:no-tzdb:2.8.1 and coudn't download android.joda

**Comment by dlew** [comment]
You need to specify that you're using an AAR:

```xml
<dependency>
    <groupId>net.danlew</groupId>
    <artifactId>android.joda</artifactId>
    <version>2.8.1</version>
    <type>aar</type>
</dependency>
```
