### ISSUE TITLE
DateTime from Long.MIN_VALUE or MAX_VALUE

### ISSUE THREAD

**Issue by OliviaLiao** [dlew/joda-time-android#84]
I try to change my library from joda time to joda-time-android. But once I use joda-time-android, it will have a problem: org.joda.time.IllegalFieldValueException Value 292278994 for year must be in the range [-292275054,292278993]. If I change Long.MIN_VALUE to Integer.MIN_VALUE, other place will have problem, like org.junit.ComparisonFailure: expected:<[2013-12-21T05:45:00.000-08:00/2013-12-21T23:40:00.000-08]:00> but was:<[1970-01-25T15:31:23.647-05:00/2013-12-22T02:40:00.000-05]:00>

**Comment by dlew** [comment]
I think I need a bit more context for why you want the year to be `Integer.MIN_VALUE`.

**Comment by OliviaLiao** [comment]
Because if I use Long.MIN_VALUE, like DateTime minTime = new DateTime(Long.MAX_VALUE); I will have a error message: org.joda.time.IllegalFieldValueException: Value 292278994 for year must be in the range [-292275054,292278993]

**Comment by dlew** [comment]
This doesn't seem like an issue with joda-time-android, but with joda-time itself.

Regardless, I would consider it alright that joda-time doesn't support further than 292 million years away.
