### ISSUE TITLE
Updating to 2.8.2: proguard issue

### ISSUE THREAD

**Issue by fred8** [dlew/joda-time-android#89]
Hello,

We just updated our dependency to the 2.8.2 release and we have now a proguard issue

org.joda.convert.TypeStringConverter: can't find referenced class com.google.common.reflect.TypeToken

Seems to be related to guava. Could we make this dependency optional, as you did for 1.8.1?

Thx!

**Comment by dlew** [comment]
joda-convert **is** optional. There must be another library including it.

Could you run `gradle dependencies` and find out who is pulling it in?

**Comment by fred8** [comment]
Just check and no dependencies on it. The problem is: it seems to refer to that dependency but the dependency cannot be resolve.

**Comment by dlew** [comment]
`TypeStringConverter` isn't in joda-time. joda-time-convert is an optional dependency. It seems odd that `TypeStringConverter` would be the one getting an error if it's not even in the library.

**Comment by dlew** [comment]
If you can provide a sample app that shows this problem I can diagnose it, but I've never heard of it before, and we even took aims to provide a proguard file for joda-time-android (so I've checked into what sort of errors occur in the past).

**Comment by fred8** [comment]
####################################################################################################
# Joda time library
####################################################################################################
-keep class org.joda.** { *; }
-dontwarn javax.xml.bind.DatatypeConverter
-dontwarn org.joda.time.tz.ZoneInfoCompiler

**Comment by dlew** [comment]
I just tested again and the sample app (for this lib) can build on 2.8.2 with no proguard issues.

I highly suspect there is more going on in your app than you realize, especially if you cannot reproduce the issue in a sample app.

**Comment by dlew** [comment]
Here's the output of `./gradlew :sample:dependencies` as well:

```
compile - Classpath for compiling the main sources.
\--- net.danlew:android.joda:2.8.2
     \--- joda-time:joda-time:2.8.2
```

No joda-convert, no guava.

**Comment by fred8** [comment]
Same here. But proguard fail

**Comment by fred8** [comment]
Your library used to have a dependency on joda-convert and we used to add joda-convert in our code to avoid a proguard issue. When we updated your lib to the last version, we also updated joda-convert which need guava. That's the all reason of the story. -> CLOSED
