### ISSUE TITLE
2.8.2 release broken

### ISSUE THREAD

**Issue by Ph1b** [dlew/joda-time-android#90]
When I use the latest release as depenency by

`compile 'net.danlew:android.joda:2.8.2'`

All the important classes like org.joda.time... are not found. When I use the version 2.8.1 everything works as intended:

`compile 'net.danlew:android.joda:2.8.1'`

**Comment by dlew** [comment]
Given that 2.8.2 has been out months now, would you consider that maybe the release isn't broken?

Try clean & build.

**Comment by Ph1b** [comment]
As I now updated again, everything seems to be in place.

The weird part was that your classes like `JodaTimeAndroid`were available but the `org.joda...` classes were not.
