### ISSUE TITLE
[Question] How to get somthing like "Today, at 13:00" with joda-time?

### ISSUE THREAD

**Issue by ch4vi** [dlew/joda-time-android#94]
I have a future date, and I'm using joda-time getRelativeDateTimeString(...) but I can't get a string that shows date and time at the same time. I need show the time always and the day (always in the future) in abbrev mode, but the flags don't work how I spect.

**Comment by dlew** [comment]
You should read the documentation [here](http://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeDateTimeString(android.content.Context, long, long, long, int)).

**Comment by ch4vi** [comment]
I solved with a mix from Android DateUtils and JodaTime Dateutils. I needed automatic translation:

```java
        //DATE Android DateUtils
        String s = DateUtils.getRelativeDateTimeString(getGlobalApplicationContext(),c.getTimeInMillis(),
                DateUtils.DAY_IN_MILLIS,DateUtils.WEEK_IN_MILLIS, flags).toString();

        String[] datetime = s.split(",");
        String date = datetime[0];

        //TIME JodaTime DateUtils
        Calendar cc = Calendar.getInstance();
        cc.set(Calendar.HOUR_OF_DAY, c.get(Calendar.HOUR_OF_DAY));
        cc.set(Calendar.MINUTE, c.get(Calendar.MINUTE));
        DateTime dt = new DateTime(cc.getTimeInMillis());
        String time = net.danlew.android.joda.DateUtils.getRelativeTimeSpanString(getGlobalApplicationContext(), dt, true).toString();

        return date+ ", " + time;
```
